// Biblioteca de cuentos de Tesis20 Nido: ocho historias originales y dos
// adaptaciones propias de clásicos («Los tres cerditos», «Caperucita Roja»).
//
// Campos opcionales de cada página para que el escenario 3D y el sonido sigan
// la narración (ver stage.playAct y cuentos-audio.playCue):
//   sfx:  ambientes suaves que suenan al abrir la página (claves de
//         cuentos-sound.json); sfxEnd: efectos que suenan al terminar de narrarla.
//   acts: acción sostenida por actor mientras dura la página
//         (blow, howl, shiver, run, build, cheer, sleep).
//   cues: por palabra narrada (clave = palabra en minúsculas sin puntuación):
//         { sfx, act: { actor: acción } } se dispara cuando la voz la pronuncia.
// Cada libro tiene 10 páginas narradas, 5 souvenirs escondidos y 5 preguntas
// finales. Los textos están escritos para niñas y niños de 3 a 6 años: frases
// cortas, vocabulario concreto y una idea por página.

export const BOOKS = [
  {
    id: "cerditos",
    title: "Los tres cerditos",
    hero: "Pipo, Lolo y Tito",
    tagline: "Tres hermanos, tres casas y un lobo que sopla",
    set: "meadow-day",
    accent: "#f4a6c1",
    // Ilustración de portada de Luis, con el título impreso: no se repinta.
    cover: { ink: "#fff1f6", sub: "#d9a3b8", image: "/assets/nido/cuentos/covers/cerditos-premium-v2.avif", titled: true },
    pages: [
      {
        t: "Tres hermanos cerditos",
        x: "Pipo, Lolo y Tito eran tres cerditos hermanos. Vivían con su mamá en una casita junto al bosque. —Ya son grandes —dijo mamá—. Cada uno hará su propia casa.",
        light: "day",
        cast: ["pipo", "lolo", "tito"],
        props: ["sol", "nubes", "casa", "arboles", "flores"],
        sfxEnd: ["cerditos-alegres"],
        acts: { pipo: "cheer" },
      },
      {
        t: "La casa de paja",
        x: "Pipo quería terminar rápido para ir a jugar. Juntó paja seca y la amontonó. En un ratito su casa estuvo lista. —¡Qué fácil! —dijo, y se fue a jugar.",
        light: "day",
        cast: ["pipo"],
        props: ["sol", "nubes", "paja", "pasto", "flores"],
        acts: { pipo: "build" },
        cues: { jugar: { act: { pipo: "cheer" } } },
      },
      {
        t: "La casa de madera",
        x: "Lolo era un poco glotón. Hizo su casa con palos de madera y tardó un poco más. Después se sentó a la sombra a comer manzanas rojas.",
        light: "day",
        cast: ["lolo"],
        props: ["sol", "madera", "arboles", "pasto"],
        pin: "manzana",
        acts: { lolo: "build" },
      },
      {
        t: "La casa de ladrillos",
        x: "Tito era muy trabajador. Puso ladrillo sobre ladrillo y los pegó con cemento. Trabajó todo el día. Al final, su casa quedó firme y bonita.",
        light: "dusk",
        cast: ["tito"],
        props: ["sol", "ladrillos", "pasto", "flores"],
        pin: "casita",
        acts: { tito: "build" },
      },
      {
        t: "Un aullido en el bosque",
        x: "Esa noche se oyó un aullido: ¡Auuu! Era el lobo, y tenía mucha hambre. Olfateó el aire y caminó derechito a la casa de paja.",
        light: "night",
        cast: ["lobo"],
        props: ["luna", "estrellas", "arboles", "paja"],
        pin: "lobo",
        cues: { auuu: { sfx: "lobo-aullido", act: { lobo: "howl" } }, derechito: { act: { lobo: "run" } } },
      },
      {
        t: "¡Soplaré y soplaré!",
        x: "—¡Ábreme la puerta, cerdito! —gritó el lobo. —¡No, no y no! —dijo Pipo. El lobo sopló y sopló, y la casa de paja voló por los aires. Pipo corrió a la casa de Lolo.",
        light: "night",
        cast: ["pipo", "lobo"],
        props: ["luna", "estrellas", "viento", "paja"],
        acts: { pipo: "shiver" },
        cues: {
          sopló: { sfx: "lobo-soplido", act: { lobo: "blow" } },
          voló: { sfx: "casa-paja" },
          corrió: { act: { pipo: "run" } },
        },
      },
      {
        t: "La casa de madera cruje",
        x: "El lobo llegó a la casa de madera. —¡Ábranme la puerta! —¡No, no y no! —dijeron los dos cerditos. El lobo sopló muy fuerte. La casa crujió y se cayó. Los dos corrieron a la casa de Tito.",
        light: "night",
        cast: ["lolo", "pipo", "lobo"],
        props: ["luna", "estrellas", "viento", "madera"],
        acts: { lolo: "shiver", pipo: "shiver" },
        cues: {
          sopló: { sfx: "lobo-soplido", act: { lobo: "blow" } },
          cayó: { sfx: "casa-madera" },
          corrieron: { act: { lolo: "run", pipo: "run" } },
        },
      },
      {
        t: "La casa que no se mueve",
        x: "—¡Ábranme o soplaré! —gritó el lobo. Sopló y sopló hasta quedarse sin aire. Pero la casa de ladrillos no se movió ni un poquito. Entonces trajo una escalera y subió al techo.",
        light: "night",
        cast: ["lobo"],
        props: ["luna", "estrellas", "ladrillos", "viento"],
        pin: "escalera",
        acts: { lobo: "blow" },
        cues: { sopló: { sfx: "lobo-soplido", act: { lobo: "blow" } }, aire: { act: { lobo: "shiver" } } },
      },
      {
        t: "¡Plaf! en la olla",
        x: "El lobo se metió por la chimenea. Pero abajo, Tito había puesto una olla de sopa muy caliente. ¡Plaf! El lobo cayó en la olla. —¡Ay, ay, qué calor! —gritó, y salió corriendo al bosque.",
        light: "moonrise",
        cast: ["tito", "lobo"],
        props: ["luna", "estrellas", "ladrillos", "olla"],
        pin: "olla",
        cues: {
          plaf: { sfx: "olla-plaf", act: { lobo: "shiver" } },
          gritó: { sfx: "lobo-ay", act: { lobo: "run" } },
          corriendo: { act: { lobo: "run", tito: "cheer" } },
        },
      },
      {
        t: "Tres casas de ladrillos",
        x: "El lobo nunca más volvió. Pipo y Lolo aprendieron que trabajar con calma vale la pena. Con la ayuda de Tito, hicieron dos casas de ladrillos. Y los tres hermanos vivieron felices y seguros.",
        light: "day",
        cast: ["pipo", "lolo", "tito"],
        props: ["sol", "nubes", "ladrillos", "flores", "pasto"],
        sfxEnd: ["cerditos-alegres"],
        acts: { pipo: "cheer", lolo: "cheer", tito: "cheer" },
      },
    ],
    quiz: [
      { q: "¿Cuántos cerditos hermanos había?", a: ["Tres", "Cinco", "Uno"] },
      { q: "¿De qué hizo Pipo su casa?", a: ["De paja", "De ladrillos", "De hielo"] },
      { q: "¿Qué comía Lolo a la sombra?", a: ["Manzanas rojas", "Helado", "Sopa"] },
      { q: "¿Qué casa no pudo tirar el lobo?", a: ["La de ladrillos", "La de paja", "La de madera"] },
      { q: "¿Dónde cayó el lobo al bajar por la chimenea?", a: ["En una olla de sopa caliente", "En una cama", "En el río"] },
    ],
  },
  {
    id: "caperucita",
    title: "Caperucita Roja",
    hero: "Caperucita",
    tagline: "Una niña, un bosque y un lobo con voz finita",
    set: "forest-day",
    accent: "#d63b3b",
    // La ilustración de portada ya trae el título impreso: `titled` evita
    // volver a pintarlo encima.
    cover: { ink: "#fff3ec", sub: "#e0a79a", image: "/assets/nido/cuentos/covers/caperucita-premium-v1.avif", titled: true },
    pages: [
      {
        t: "La caperuza roja",
        x: "Había una vez una niña muy querida por todos. Su abuelita le regaló una caperuza roja que le quedaba tan bien que nunca se la quitaba. Por eso todos la llamaban Caperucita Roja.",
        light: "day",
        cast: ["caperucita"],
        props: ["sol", "nubes", "casa", "flores", "pasto"],
        pin: "caperuza",
      },
      {
        t: "Un encargo para la abuelita",
        x: "Un día su mamá le dijo: —La abuelita está enfermita. Llévale este pastel y este jugo en la canasta. Ve por el sendero y no te apartes de él. —Sí, mamá —dijo Caperucita, y salió contenta.",
        light: "day",
        cast: ["caperucita"],
        props: ["sol", "casa", "sendero", "flores", "arboles"],
        pin: "canasta",
        cues: { contenta: { sfx: "pasos-bosque", act: { caperucita: "run" } } },
      },
      {
        t: "El lobo del bosque",
        x: "En el bosque, Caperucita se encontró con un lobo. Ella no sabía que los lobos son peligrosos y no tuvo miedo. —¿A dónde vas tan temprano? —preguntó el lobo. —A casa de mi abuelita, junto a los tres robles.",
        light: "day",
        cast: ["caperucita", "lobo"],
        props: ["arboles", "sendero", "hojas", "pasto"],
        pin: "pajarito",
        sfx: ["pajaros"],
      },
      {
        t: "Las flores del bosque",
        x: "—Mira qué lindas flores —dijo el lobo—. ¿Por qué no le llevas algunas? Caperucita se salió del sendero para cortar flores. Cortaba una, y otra, y otra más. Mientras tanto, el lobo corrió a la casa de la abuelita.",
        light: "day",
        cast: ["caperucita", "mariposa"],
        props: ["arboles", "flores", "sol", "pasto"],
        pin: "ramo",
      },
      {
        t: "Toc, toc",
        x: "El lobo tocó la puerta de la abuelita. —¿Quién es? —Soy Caperucita —dijo el lobo con voz finita. —Pasa, hijita, la puerta está abierta. El lobo entró y, de un solo bocado, se tragó a la abuelita enterita.",
        light: "dusk",
        cast: ["lobo"],
        props: ["casa", "arboles", "sendero", "flores"],
        cues: { tocó: { sfx: "toc-toc" }, bocado: { act: { lobo: "blow" } } },
      },
      {
        t: "Disfrazado de abuelita",
        x: "Después se puso el camisón y el gorro de dormir de la abuelita. Se metió en la cama y se tapó hasta la nariz. Y esperó, muy quieto, a que llegara Caperucita.",
        light: "day",
        cast: ["lobo-cama"],
        props: ["cuarto"],
        acts: { "lobo-cama": "sleep" },
      },
      {
        t: "¡Qué orejas tan grandes!",
        x: "Caperucita llegó y entró despacito. —Abuelita, ¡qué orejas tan grandes tienes! —Son para oírte mejor. —¡Y qué ojos tan grandes! —Son para verte mejor. —¡Y qué boca tan grande! —¡Es para comerte mejor!",
        light: "day",
        cast: ["caperucita", "lobo-cama"],
        props: ["cuarto"],
        pin: "gorro",
      },
      {
        t: "El cazador",
        x: "El lobo saltó de la cama y también se tragó a Caperucita. Con la panza llena, se durmió y roncó muy fuerte. Un cazador que pasaba por ahí oyó los ronquidos y entró a ver qué pasaba.",
        light: "day",
        cast: ["cazador", "lobo-cama"],
        props: ["cuarto"],
        acts: { "lobo-cama": "sleep" },
        cues: { roncó: { sfx: "lobo-ronquido" } },
      },
      {
        t: "¡Sanas y salvas!",
        x: "El cazador abrió con cuidado la panza del lobo dormido. Primero salió Caperucita y después la abuelita, ¡las dos sanas y salvas! Le llenaron la panza de piedras, y el lobo, al despertar, se fue muy lejos y nunca más volvió.",
        light: "dusk",
        cast: ["caperucita", "abuelita", "cazador"],
        props: ["casa", "arboles", "piedras", "pasto"],
        acts: { caperucita: "cheer" },
        sfxEnd: ["cerditos-alegres"],
      },
      {
        t: "Por el sendero",
        x: "La abuelita comió el pastel y se sintió mucho mejor. Caperucita la abrazó fuerte y prometió: —Nunca más me saldré del sendero. Y las dos vivieron felices en el bosque.",
        light: "day",
        cast: ["caperucita", "abuelita"],
        props: ["casa", "sol", "flores", "sendero", "pasto"],
        cues: { abrazó: { sfx: "abuelita-abrazo", act: { caperucita: "cheer", abuelita: "cheer" } } },
      },
    ],
    quiz: [
      { q: "¿De qué color era la caperuza?", a: ["Roja", "Azul", "Verde"] },
      { q: "¿Qué llevaba Caperucita en la canasta?", a: ["Un pastel y jugo", "Piedras", "Juguetes"] },
      { q: "¿Por qué se salió del sendero?", a: ["Para cortar flores", "Para dormir", "Para nadar"] },
      { q: "¿Quién se puso el gorro de la abuelita?", a: ["El lobo", "El cazador", "Un pajarito"] },
      { q: "¿Quién ayudó a Caperucita y a la abuelita?", a: ["El cazador", "El lobo", "La mamá"] },
    ],
  },
  {
    id: "kusi",
    title: "Kusi y la luna dormilona",
    hero: "Kusi",
    tagline: "Un osito de anteojos quiere despertar a la luna",
    set: "andes-night",
    accent: "#f5c451",
    cover: { ink: "#fdf2d0", sub: "#c9b489", image: "/assets/nido/cuentos/covers/kusi-premium-v1.avif" },
    pages: [
      {
        t: "El bosque de nubes",
        x: "Kusi era un osito de anteojos. Vivía muy arriba, en un bosque de nubes. Cada noche subía a su piedra favorita para mirar la luna.",
        light: "night",
        cast: ["oso"],
        props: ["montanas", "luna", "estrellas"],
      },
      {
        t: "La luna no llegó",
        x: "Pero esa noche la luna no llegó. El cielo estaba oscuro y callado. —¿Dónde estás? —preguntó Kusi bajito.",
        light: "night",
        cast: ["oso"],
        props: ["montanas", "estrellas", "nubes"],
      },
      {
        t: "El búho sabio",
        x: "Un búho abrió un ojo desde su rama. —La luna se quedó dormida —dijo—. A veces la luna también se cansa.",
        light: "night",
        cast: ["oso", "buho"],
        props: ["arboles", "estrellas"],
        pin: "buho",
      },
      {
        t: "Una idea con luz",
        x: "Kusi encendió su farol de vidrio. —Si le llevo una luz, tal vez despierte —pensó. Y empezó a caminar cuesta arriba.",
        light: "night",
        cast: ["oso"],
        props: ["farol", "montanas", "estrellas"],
        pin: "farol",
      },
      {
        t: "El puente delgado",
        x: "En el camino había un puente muy delgado. Kusi respiró hondo. Puso una pata, luego la otra, y cruzó despacito.",
        light: "night",
        cast: ["oso"],
        props: ["puente", "montanas", "estrellas"],
      },
      {
        t: "La miel del panal",
        x: "Unas abejas dormidas le regalaron miel. —Para el camino —zumbaron. Kusi guardó el panal en su bolsita.",
        light: "night",
        cast: ["oso"],
        props: ["panal", "arboles", "estrellas"],
        pin: "panal",
      },
      {
        t: "La cima",
        x: "Al final llegó a la cima más alta del bosque. Desde ahí el cielo se veía enorme. Kusi levantó su farol con las dos patas.",
        light: "night",
        cast: ["oso"],
        props: ["montanas", "estrellas", "farol"],
      },
      {
        t: "Un canto pequeñito",
        x: "Kusi cantó una canción muy suave. No era fuerte, pero era suya. El viento la llevó hacia arriba.",
        light: "night",
        cast: ["oso"],
        props: ["estrellas", "nubes", "montanas"],
        pin: "estrella",
      },
      {
        t: "La luna abre los ojos",
        x: "Entonces una luz tibia se encendió en el cielo. La luna abrió los ojos y sonrió. —Gracias por esperarme —dijo.",
        light: "moonrise",
        cast: ["oso"],
        props: ["luna", "estrellas", "montanas"],
        pin: "luna",
      },
      {
        t: "Buenas noches",
        x: "Kusi volvió a su piedra con la luna encendida. Cerró los ojos contento. En el bosque de nubes todos durmieron tranquilos.",
        light: "moonrise",
        cast: ["oso"],
        props: ["luna", "arboles", "estrellas"],
      },
    ],
    quiz: [
      { q: "¿Qué animal es Kusi?", a: ["Un osito de anteojos", "Un zorro", "Una tortuga"] },
      { q: "¿Qué le pasó a la luna?", a: ["Se quedó dormida", "Se fue de viaje", "Se puso a llover"] },
      { q: "¿Quién le contó el secreto a Kusi?", a: ["Un búho", "Un pez", "Un tren"] },
      { q: "¿Qué llevó Kusi para despertarla?", a: ["Un farol", "Una pelota", "Un sombrero"] },
      { q: "¿Qué hizo Kusi en la cima?", a: ["Cantó una canción suave", "Se puso a correr", "Se escondió"] },
    ],
  },
  {
    id: "amaru",
    title: "Amaru y el río de estrellas",
    hero: "Amaru",
    tagline: "Un bufeo rosado busca las luces que se apagaron",
    set: "amazon-river",
    accent: "#7fd7c4",
    cover: { ink: "#eafaf4", sub: "#8fb9ad", image: "/assets/nido/cuentos/covers/amaru-premium-v1.avif" },
    pages: [
      {
        t: "El río que brillaba",
        x: "Amaru era un bufeo rosado. Vivía en un río grande de la selva. Por las noches el agua brillaba como un cielo al revés.",
        light: "night",
        cast: ["bufeo"],
        props: ["selva", "luciernagas", "estrellas"],
      },
      {
        t: "Una noche apagada",
        x: "Una noche el río se puso oscuro. Ninguna luz flotaba en el agua. Amaru dio una vuelta y no encontró ni una chispa.",
        light: "night",
        cast: ["bufeo"],
        props: ["selva", "agua", "nubes"],
      },
      {
        t: "La rana mensajera",
        x: "Una ranita saltó a una hoja enorme. —Las luciérnagas se escondieron —croó—. Tienen miedo de la tormenta.",
        light: "night",
        cast: ["bufeo", "rana"],
        props: ["nenufar", "selva"],
        pin: "nenufar",
      },
      {
        t: "Río arriba",
        x: "Amaru nadó río arriba, entre raíces y hojas. El agua estaba fresca y silenciosa. Solo se oía su respiración.",
        light: "night",
        cast: ["bufeo"],
        props: ["selva", "agua", "raices"],
      },
      {
        t: "La canoa vacía",
        x: "Encontró una canoa dormida junto a la orilla. Adentro había un remo y una flor. Amaru la empujó con el hocico, muy suave.",
        light: "night",
        cast: ["bufeo"],
        props: ["canoa", "selva"],
        pin: "canoa",
      },
      {
        t: "El pez linterna",
        x: "Un pez pequeñito salió de una cueva. Tenía una luz azul en la frente. —Yo también me escondí —dijo temblando.",
        light: "night",
        cast: ["bufeo", "pez"],
        props: ["cueva", "agua"],
        pin: "pez",
      },
      {
        t: "Un plan valiente",
        x: "—Si brillamos juntos, la noche da menos miedo —dijo Amaru. El pececito lo pensó un momento. Después dijo que sí.",
        light: "night",
        cast: ["bufeo", "pez"],
        props: ["agua", "selva"],
      },
      {
        t: "Las luciérnagas vuelven",
        x: "El pez encendió su luz. Una luciérnaga se acercó, y luego otra, y luego cien. El río empezó a brillar otra vez.",
        light: "night",
        cast: ["bufeo"],
        props: ["luciernagas", "selva", "agua"],
        pin: "luciernaga",
      },
      {
        t: "El cielo al revés",
        x: "El agua se llenó de puntitos dorados. Parecía que las estrellas se habían mudado al río. Amaru dio un salto de alegría.",
        light: "night",
        cast: ["bufeo"],
        props: ["luciernagas", "estrellas", "agua"],
      },
      {
        t: "Nadie brilla solo",
        x: "Desde esa noche, el pececito nada al lado de Amaru. Aprendieron algo importante: la luz se hace más grande cuando se comparte.",
        light: "dawn",
        cast: ["bufeo", "pez"],
        props: ["selva", "agua", "estrellas"],
        pin: "bufeo",
      },
    ],
    quiz: [
      { q: "¿Qué animal es Amaru?", a: ["Un bufeo rosado", "Un cocodrilo", "Una llama"] },
      { q: "¿Qué pasó una noche en el río?", a: ["Se quedó oscuro", "Se congeló", "Se secó"] },
      { q: "¿Quién le avisó a Amaru?", a: ["Una ranita", "Un búho", "Una abeja"] },
      { q: "¿Qué tenía el pececito en la frente?", a: ["Una luz azul", "Un sombrero", "Una hoja"] },
      { q: "¿Qué aprendieron al final?", a: ["La luz se comparte", "Hay que nadar rápido", "Es mejor esconderse"] },
    ],
  },
  {
    id: "sami",
    title: "Sami y la cometa viajera",
    hero: "Sami",
    tagline: "Una cometa se escapa y cruza todo el valle",
    set: "highland-day",
    accent: "#ff9d6c",
    cover: { ink: "#fff3e6", sub: "#c99a7a", image: "/assets/nido/cuentos/covers/sami-premium-v1.avif" },
    pages: [
      {
        t: "Viento de agosto",
        x: "Sami vivía en un valle de montañas verdes. En agosto llegaba el viento fuerte. Ese era el mes de volar cometas.",
        light: "day",
        cast: ["nina"],
        props: ["montanas", "flores", "nubes"],
      },
      {
        t: "La cometa nueva",
        x: "Su abuela le hizo una cometa de papel rojo. Tenía una cola larga con lazos de colores. Sami la abrazó fuerte.",
        light: "day",
        cast: ["nina"],
        props: ["cometa", "casa", "flores"],
        pin: "cometa",
      },
      {
        t: "¡Se escapó!",
        x: "Sami corrió y la cometa subió altísimo. De pronto el hilo se soltó de su mano. La cometa se fue volando sobre el cerro.",
        light: "day",
        cast: ["nina"],
        props: ["cometa", "montanas", "nubes"],
      },
      {
        t: "Las ovejas",
        x: "Sami corrió detrás. Pasó junto a un rebaño de ovejas gordas. —¿La vieron? —preguntó. Las ovejas miraron hacia arriba.",
        light: "day",
        cast: ["nina", "oveja"],
        props: ["pasto", "montanas"],
        pin: "oveja",
      },
      {
        t: "El sombrero volador",
        x: "El viento también se llevó su sombrero. Sami se rió mientras corría. Ahora tenía dos cosas que alcanzar.",
        light: "day",
        cast: ["nina"],
        props: ["sombrero", "pasto", "nubes"],
        pin: "sombrero",
      },
      {
        t: "El campo de flores",
        x: "Cruzó un campo lleno de flores amarillas. Las abejas zumbaban contentas. La cometa se veía chiquita a lo lejos.",
        light: "day",
        cast: ["nina"],
        props: ["flores", "montanas", "cometa"],
        pin: "flor",
      },
      {
        t: "La campana del pueblo",
        x: "Sonó la campana del pueblo. Din, don. Sami levantó la vista y vio algo rojo sobre la torre.",
        light: "day",
        cast: ["nina"],
        props: ["campana", "casa"],
        pin: "campana",
      },
      {
        t: "Enredada",
        x: "La cometa estaba enredada en la torre. Estaba muy alto para alcanzarla. Sami se quedó pensando.",
        light: "day",
        cast: ["nina"],
        props: ["campana", "cometa", "nubes"],
      },
      {
        t: "El viento ayuda",
        x: "Entonces sopló otra vez el viento. La cometa se soltó sola y bajó girando. Sami abrió los brazos y la atrapó.",
        light: "day",
        cast: ["nina"],
        props: ["cometa", "flores", "nubes"],
      },
      {
        t: "De vuelta a casa",
        x: "Sami volvió a casa con la cometa y el sombrero. Le contó todo a su abuela. Y mañana la volverían a volar.",
        light: "dusk",
        cast: ["nina"],
        props: ["casa", "montanas", "cometa"],
      },
    ],
    quiz: [
      { q: "¿Quién le hizo la cometa a Sami?", a: ["Su abuela", "Su maestra", "Un vecino"] },
      { q: "¿De qué color era la cometa?", a: ["Roja", "Verde", "Azul"] },
      { q: "¿Qué animales encontró en el camino?", a: ["Ovejas", "Peces", "Monos"] },
      { q: "¿Dónde se enredó la cometa?", a: ["En la torre de la campana", "En un árbol", "En el río"] },
      { q: "¿Qué la ayudó a soltarse?", a: ["El viento", "La lluvia", "Un perro"] },
    ],
  },
  {
    id: "killa",
    title: "Killa y el zorro del desierto",
    hero: "Killa",
    tagline: "Una noche de arena, estrellas y huellas",
    set: "desert-night",
    accent: "#c9a3ff",
    cover: { ink: "#f3ecff", sub: "#a58fc7", image: "/assets/nido/cuentos/covers/killa-premium-v1.avif" },
    pages: [
      {
        t: "Arena fría",
        x: "En el desierto, de noche, la arena se pone fría. Killa era una zorrita de orejas grandes. Salía a caminar cuando salían las estrellas.",
        light: "night",
        cast: ["zorro"],
        props: ["dunas", "estrellas", "cactus"],
      },
      {
        t: "Una estrella que cae",
        x: "Esa noche vio una estrella caer detrás de una duna. Hizo un ruidito suave, como una campanita. Killa movió las orejas.",
        light: "night",
        cast: ["zorro"],
        props: ["dunas", "estrella", "estrellas"],
        pin: "estrella",
      },
      {
        t: "Huellas en la arena",
        x: "Siguió unas huellas pequeñitas. Subían y bajaban por la arena. Killa caminó despacio para no perderlas.",
        light: "night",
        cast: ["zorro"],
        props: ["huellas", "dunas"],
      },
      {
        t: "El cactus con flor",
        x: "Encontró un cactus alto con una flor blanca. La flor solo se abre de noche. Killa la olió con cuidado, sin picarse.",
        light: "night",
        cast: ["zorro"],
        props: ["cactus", "dunas", "estrellas"],
        pin: "cactus",
      },
      {
        t: "La vasija antigua",
        x: "Entre las piedras había una vasija de barro. Tenía dibujos de pájaros muy antiguos. Adentro dormía un escarabajo.",
        light: "night",
        cast: ["zorro"],
        props: ["vasija", "piedras"],
        pin: "vasija",
      },
      {
        t: "Las líneas del suelo",
        x: "Desde lo alto de la duna, Killa vio unas líneas gigantes en el suelo. Dibujaban un colibrí. Alguien las hizo hace muchísimo tiempo.",
        light: "night",
        cast: ["zorro"],
        props: ["lineas", "dunas", "estrellas"],
        pin: "colibri",
      },
      {
        t: "El viento borra",
        x: "El viento empezó a soplar y borró las huellas. Killa se quedó quieta. Ya no sabía por dónde seguir.",
        light: "night",
        cast: ["zorro"],
        props: ["dunas", "viento"],
      },
      {
        t: "Mirar hacia arriba",
        x: "Entonces levantó la cabeza. Las estrellas seguían ahí, brillando en fila. Killa entendió: podía guiarse con el cielo.",
        light: "night",
        cast: ["zorro"],
        props: ["estrellas", "dunas"],
      },
      {
        t: "El regalo del cielo",
        x: "Detrás de la última duna encontró la estrella caída. Era una piedra tibia que brillaba en su hocico. Killa la llevó con orgullo.",
        light: "night",
        cast: ["zorro"],
        props: ["estrella", "dunas", "estrellas"],
      },
      {
        t: "Casa de arena",
        x: "Killa volvió a su cueva y guardó la piedra. Cuando extraña el cielo, la mira brillar. Y se duerme contenta.",
        light: "dawn",
        cast: ["zorro"],
        props: ["dunas", "cactus", "estrella"],
        pin: "zorro",
      },
    ],
    quiz: [
      { q: "¿Qué animal es Killa?", a: ["Una zorrita", "Una oveja", "Un pingüino"] },
      { q: "¿Qué vio caer del cielo?", a: ["Una estrella", "Una hoja", "Una pelota"] },
      { q: "¿Qué dibujaban las líneas gigantes?", a: ["Un colibrí", "Un barco", "Una casa"] },
      { q: "¿Qué borró las huellas?", a: ["El viento", "La lluvia", "El mar"] },
      { q: "¿Con qué se guio al final?", a: ["Con las estrellas", "Con un mapa", "Con su olfato"] },
    ],
  },
  {
    id: "chaska",
    title: "Chaska y la flor de cristal",
    hero: "Chaska",
    tagline: "Un picaflor cruza la niebla para llegar a tiempo",
    set: "cloud-forest",
    accent: "#8ed2a0",
    cover: { ink: "#eefaf0", sub: "#8fb99a", image: "/assets/nido/cuentos/covers/chaska-premium-v1.avif" },
    pages: [
      {
        t: "Alas rapidísimas",
        x: "Chaska era un picaflor muy pequeño. Sus alas hacían un ruido suave: fru, fru, fru. Podía quedarse quieto en el aire.",
        light: "day",
        cast: ["picaflor"],
        props: ["arboles", "niebla", "flores"],
      },
      {
        t: "El secreto del bosque",
        x: "Una mariposa le contó un secreto. —Hoy se abre la flor de cristal —dijo—. Solo se abre una vez al año.",
        light: "day",
        cast: ["picaflor", "mariposa"],
        props: ["hojas", "niebla"],
        pin: "mariposa",
      },
      {
        t: "Muy lejos",
        x: "La flor crecía al otro lado del bosque. Chaska nunca había volado tan lejos. Pero quería verla con sus propios ojos.",
        light: "day",
        cast: ["picaflor"],
        props: ["arboles", "niebla"],
      },
      {
        t: "La niebla espesa",
        x: "En el camino todo se puso blanco. La niebla tapaba las ramas y el cielo. Chaska voló despacito, escuchando el agua.",
        light: "mist",
        cast: ["picaflor"],
        props: ["niebla", "arboles"],
      },
      {
        t: "La gota grande",
        x: "Se posó en una hoja para descansar. Una gota enorme rodó hasta su pico. Chaska bebió y sintió fuerzas nuevas.",
        light: "mist",
        cast: ["picaflor"],
        props: ["gota", "hojas"],
        pin: "gota",
      },
      {
        t: "El árbol viejo",
        x: "Pasó junto a un árbol lleno de musgo. —Sigue el sonido del río —crujió el árbol. Chaska le dio las gracias.",
        light: "mist",
        cast: ["picaflor"],
        props: ["arboles", "musgo", "niebla"],
      },
      {
        t: "La orquídea escondida",
        x: "Entre las raíces vio una orquídea morada. No era la flor que buscaba, pero era hermosa. Chaska se quedó un momentito.",
        light: "mist",
        cast: ["picaflor"],
        props: ["orquidea", "raices"],
        pin: "orquidea",
      },
      {
        t: "La luz se abre",
        x: "El sol rompió la niebla de golpe. Todo el bosque se puso dorado. Y ahí estaba: la flor de cristal, temblando.",
        light: "day",
        cast: ["picaflor"],
        props: ["flor-cristal", "arboles", "sol"],
        pin: "flor-cristal",
      },
      {
        t: "Un sorbo de estrella",
        x: "Chaska bebió su néctar dulcísimo. Sabía a lluvia y a miel al mismo tiempo. La flor le regaló un brillo en las plumas.",
        light: "day",
        cast: ["picaflor"],
        props: ["flor-cristal", "niebla"],
      },
      {
        t: "Volver contando",
        x: "Chaska voló de regreso a contarlo todo. Ahora otros pájaros quieren ir el año que viene. Y él ya sabe el camino.",
        light: "dusk",
        cast: ["picaflor", "mariposa"],
        props: ["arboles", "nubes"],
        pin: "picaflor",
      },
    ],
    quiz: [
      { q: "¿Qué es Chaska?", a: ["Un picaflor", "Un zorro", "Una rana"] },
      { q: "¿Quién le contó el secreto?", a: ["Una mariposa", "Un búho", "Una oveja"] },
      { q: "¿Cada cuánto se abre la flor de cristal?", a: ["Una vez al año", "Todos los días", "Nunca"] },
      { q: "¿Qué tapaba el camino?", a: ["La niebla", "La nieve", "La arena"] },
      { q: "¿Qué hizo Chaska al final?", a: ["Volvió a contarlo", "Se quedó a vivir ahí", "Se durmió"] },
    ],
  },
  {
    id: "tico",
    title: "Tico y el tren de las nubes",
    hero: "Tico",
    tagline: "Un tren pequeño sube hasta donde vive la neblina",
    set: "mountain-day",
    accent: "#7fb6ff",
    cover: { ink: "#eaf3ff", sub: "#8ba7c9", image: "/assets/nido/cuentos/covers/tico-premium-v1.avif" },
    pages: [
      {
        t: "La estación chiquita",
        x: "Tico vivía al lado de una estación muy pequeña. Solo pasaba un tren, y pasaba una vez por semana. Tico lo esperaba siempre.",
        light: "day",
        cast: ["nino"],
        props: ["estacion", "montanas", "tren"],
      },
      {
        t: "Un boleto de papel",
        x: "Un día el maquinista le regaló un boleto. —Hoy subimos hasta las nubes —dijo. Tico guardó el boleto en su bolsillo.",
        light: "day",
        cast: ["nino", "maquinista"],
        props: ["boleto", "tren"],
        pin: "boleto",
      },
      {
        t: "Chu, chu",
        x: "El tren arrancó despacito. Chu, chu, chu. Las casas se hicieron pequeñitas allá abajo.",
        light: "day",
        cast: ["nino"],
        props: ["tren", "casa", "montanas"],
        pin: "tren",
      },
      {
        t: "Las vicuñas",
        x: "En la ladera había vicuñas doradas. Levantaron la cabeza para ver pasar el tren. Tico las saludó por la ventana.",
        light: "day",
        cast: ["vicuna"],
        props: ["pasto", "montanas", "tren"],
        pin: "vicuna",
      },
      {
        t: "El puente altísimo",
        x: "El tren cruzó un puente de fierro sobre un abismo. Tico apretó fuerte su boleto. Pero no cerró los ojos.",
        light: "day",
        cast: ["nino"],
        props: ["puente", "montanas", "tren"],
        pin: "puente",
      },
      {
        t: "El aire delgado",
        x: "Cada vez había menos aire y más frío. Tico se puso su chullo de lana. La montaña se veía blanca en la punta.",
        light: "day",
        cast: ["nino"],
        props: ["nieve", "montanas"],
      },
      {
        t: "Entrar a una nube",
        x: "De pronto todo se puso blanco y suave. ¡Estaban dentro de una nube! Tico sacó la mano y no vio sus dedos.",
        light: "mist",
        cast: ["nino"],
        props: ["nubes", "tren"],
      },
      {
        t: "El silbato",
        x: "El maquinista tocó el silbato: ¡fiuuu! El sonido rebotó en las montañas. Volvió tres veces, como un juego.",
        light: "mist",
        cast: ["maquinista"],
        props: ["silbato", "nubes"],
        pin: "silbato",
      },
      {
        t: "Arriba del todo",
        x: "El tren se detuvo en la cumbre. El cielo estaba tan cerca que parecía tocarse. Tico respiró hondo y sonrió.",
        light: "day",
        cast: ["nino"],
        props: ["montanas", "nubes", "sol"],
      },
      {
        t: "Bajar contando",
        x: "De regreso, Tico contó cada curva del camino. Guardó su boleto en una cajita. Es su recuerdo favorito.",
        light: "dusk",
        cast: ["nino"],
        props: ["tren", "montanas", "boleto"],
      },
    ],
    quiz: [
      { q: "¿Qué le regaló el maquinista?", a: ["Un boleto", "Un dulce", "Una pelota"] },
      { q: "¿Qué animales vio en la ladera?", a: ["Vicuñas", "Ballenas", "Ranas"] },
      { q: "¿Qué cruzó el tren?", a: ["Un puente altísimo", "Un río", "Un túnel de arena"] },
      { q: "¿Qué pasó cuando entraron a la nube?", a: ["Todo se puso blanco", "Se hizo de noche", "Empezó a nevar"] },
      { q: "¿Dónde guardó Tico su boleto?", a: ["En una cajita", "En la basura", "En el río"] },
    ],
  },
  {
    id: "ana",
    title: "Ana y la ballena",
    hero: "Ana",
    tagline: "En la orilla del mar se puede escuchar muy lejos",
    set: "ocean-day",
    accent: "#5fc8e8",
    cover: { ink: "#e8f8ff", sub: "#7ba9bd", image: "/assets/nido/cuentos/covers/ana-premium-v1.avif" },
    pages: [
      {
        t: "La niña de la orilla",
        x: "Ana vivía frente al mar. Cada mañana caminaba por la arena mojada. Le gustaba juntar caracolas.",
        light: "day",
        cast: ["nina2"],
        props: ["mar", "caracola", "sol"],
        pin: "caracola",
      },
      {
        t: "Un sonido raro",
        x: "Una mañana el mar estaba muy callado. Faltaba algo, pero Ana no sabía qué. El agua se movía sin cantar.",
        light: "day",
        cast: ["nina2"],
        props: ["mar", "nubes"],
      },
      {
        t: "El pelícano lo sabe",
        x: "Un pelícano se posó en una roca. —La ballena perdió su canción —dijo—. Hace días que no se le oye.",
        light: "day",
        cast: ["nina2", "pelicano"],
        props: ["roca", "mar"],
        pin: "pelicano",
      },
      {
        t: "La caracola grande",
        x: "Ana buscó su caracola más grande. Se la puso en la oreja y escuchó el mar adentro. Tuvo una idea.",
        light: "day",
        cast: ["nina2"],
        props: ["caracola", "arena"],
      },
      {
        t: "Cantar hacia el agua",
        x: "Ana cantó dentro de la caracola, mirando al mar. Su voz salió redonda y viajera. Las olas la llevaron mar adentro.",
        light: "day",
        cast: ["nina2"],
        props: ["mar", "olas"],
        pin: "ola",
      },
      {
        t: "Algo grande se acerca",
        x: "El agua se movió muy despacio. Apareció una sombra enorme y azul. Ana no tuvo miedo: se quedó quieta.",
        light: "day",
        cast: ["nina2", "ballena"],
        props: ["mar", "nubes"],
      },
      {
        t: "La ballena escucha",
        x: "La ballena sacó la cabeza y escuchó. La canción de Ana le sonó conocida. Movió la cola con cuidado.",
        light: "day",
        cast: ["ballena"],
        props: ["mar", "sol"],
        pin: "ballena",
      },
      {
        t: "La primera nota",
        x: "Entonces la ballena hizo un sonido bajito. Luego otro más largo. Poco a poco recordó toda su canción.",
        light: "day",
        cast: ["ballena"],
        props: ["mar", "olas"],
      },
      {
        t: "El mar canta otra vez",
        x: "El sonido llenó toda la bahía. Las estrellas de mar temblaron de gusto. Ana aplaudió con los pies en el agua.",
        light: "dusk",
        cast: ["nina2", "ballena"],
        props: ["mar", "estrella-mar"],
        pin: "estrella-mar",
      },
      {
        t: "Amigas de lejos",
        x: "Ahora, cada tarde, Ana canta desde la orilla. Y desde muy lejos, la ballena le contesta. Aunque no se vean, se escuchan.",
        light: "dusk",
        cast: ["nina2"],
        props: ["mar", "sol", "caracola"],
      },
    ],
    quiz: [
      { q: "¿Qué juntaba Ana en la playa?", a: ["Caracolas", "Piedras rojas", "Hojas"] },
      { q: "¿Qué le pasó a la ballena?", a: ["Perdió su canción", "Perdió su cola", "Se durmió"] },
      { q: "¿Quién le contó a Ana?", a: ["Un pelícano", "Un zorro", "Una rana"] },
      { q: "¿Qué usó Ana para cantar?", a: ["Una caracola", "Un tambor", "Una flauta"] },
      { q: "¿Qué hacen ahora cada tarde?", a: ["Se cantan de lejos", "Juegan en la arena", "Duermen"] },
    ],
  },
  {
    id: "wayra",
    title: "Wayra y el bosque que canta",
    hero: "Wayra",
    tagline: "Una vicuñita descubre de dónde viene la música",
    set: "forest-dusk",
    accent: "#f2a0b5",
    cover: { ink: "#fdeef2", sub: "#c294a2", image: "/assets/nido/cuentos/covers/wayra-premium-v1.avif" },
    pages: [
      {
        t: "Orejas atentas",
        x: "Wayra era una vicuñita curiosa. Tenía las orejas siempre paradas. Escuchaba cosas que nadie más escuchaba.",
        light: "dusk",
        cast: ["vicuna"],
        props: ["pasto", "montanas", "sol"],
      },
      {
        t: "Una música lejana",
        x: "Una tarde oyó una música muy suave. Venía del bosque de abajo. Wayra bajó la ladera trotando.",
        light: "dusk",
        cast: ["vicuna"],
        props: ["arboles", "montanas"],
      },
      {
        t: "Las hojas del viento",
        x: "Al entrar, las hojas sonaban como lluvia. Shhh, shhh. Wayra se quedó quieta para escuchar mejor.",
        light: "dusk",
        cast: ["vicuna"],
        props: ["hojas", "arboles"],
        pin: "hoja",
      },
      {
        t: "El tambor del tronco",
        x: "Un pájaro carpintero golpeaba un tronco. Toc, toc, toc. Era el tambor del bosque.",
        light: "dusk",
        cast: ["vicuna", "carpintero"],
        props: ["tronco", "arboles"],
        pin: "tambor",
      },
      {
        t: "El agua que canta",
        x: "Más adentro había un arroyo saltarín. El agua golpeaba las piedras. Cada piedra sonaba distinto.",
        light: "dusk",
        cast: ["vicuna"],
        props: ["arroyo", "piedras"],
      },
      {
        t: "Las luciérnagas bailan",
        x: "Cuando oscureció salieron luces pequeñitas. Subían y bajaban al ritmo del agua. Wayra movió la cabeza siguiéndolas.",
        light: "night",
        cast: ["vicuna"],
        props: ["luciernagas", "arboles"],
        pin: "luciernaga",
      },
      {
        t: "La quena olvidada",
        x: "Entre las raíces encontró una quena de caña. Alguien la había olvidado hace mucho. El viento pasaba por ella y sonaba solita.",
        light: "night",
        cast: ["vicuna"],
        props: ["quena", "raices"],
        pin: "quena",
      },
      {
        t: "Todo junto",
        x: "Wayra entendió el secreto. El bosque no tenía un solo músico. Cantaban todos a la vez, cada uno con su sonido.",
        light: "night",
        cast: ["vicuna"],
        props: ["arboles", "luciernagas", "estrellas"],
      },
      {
        t: "Su propia nota",
        x: "Wayra respiró y soltó un sonido suave. Su voz se mezcló con el agua y las hojas. Ahora ella también era parte de la música.",
        light: "night",
        cast: ["vicuna"],
        props: ["arboles", "estrellas"],
        pin: "vicuna",
      },
      {
        t: "Volver a escuchar",
        x: "Cada tarde Wayra vuelve al bosque a escuchar. Nunca suena exactamente igual. Por eso siempre vale la pena volver.",
        light: "dusk",
        cast: ["vicuna"],
        props: ["arboles", "montanas", "sol"],
      },
    ],
    quiz: [
      { q: "¿Qué animal es Wayra?", a: ["Una vicuñita", "Una ballena", "Un búho"] },
      { q: "¿Qué escuchó una tarde?", a: ["Una música lejana", "Un trueno", "Un tren"] },
      { q: "¿Quién hacía el tambor del bosque?", a: ["Un pájaro carpintero", "Una rana", "El viento"] },
      { q: "¿Qué encontró entre las raíces?", a: ["Una quena", "Una pelota", "Un boleto"] },
      { q: "¿Cuál era el secreto del bosque?", a: ["Cantaban todos juntos", "Había un solo músico", "Nadie cantaba"] },
    ],
  },
];

export const PIN_LABELS = {
  caperuza: "Caperuza roja",
  canasta: "Canasta con pastel",
  pajarito: "Pajarito del bosque",
  ramo: "Ramo de flores",
  gorro: "Gorro de la abuelita",
  manzana: "Manzana de Lolo",
  casita: "Casita de ladrillos",
  lobo: "Lobo soplador",
  escalera: "Escalera del lobo",
  olla: "Olla de sopa caliente",
  buho: "Búho del bosque",
  farol: "Farol de vidrio",
  panal: "Panal de miel",
  estrella: "Estrella cantora",
  luna: "Luna dormilona",
  nenufar: "Hoja de nenúfar",
  canoa: "Canoa dormida",
  pez: "Pez linterna",
  luciernaga: "Luciérnaga",
  bufeo: "Bufeo rosado",
  cometa: "Cometa de papel",
  oveja: "Oveja del cerro",
  sombrero: "Sombrero volador",
  flor: "Flor amarilla",
  campana: "Campana del pueblo",
  cactus: "Cactus florecido",
  vasija: "Vasija antigua",
  colibri: "Colibrí de arena",
  zorro: "Zorrita Killa",
  boleto: "Boleto de papel",
  tren: "Tren de las nubes",
  vicuna: "Vicuña dorada",
  puente: "Puente de fierro",
  silbato: "Silbato del tren",
  mariposa: "Mariposa mensajera",
  gota: "Gota de rocío",
  orquidea: "Orquídea morada",
  "flor-cristal": "Flor de cristal",
  picaflor: "Picaflor Chaska",
  caracola: "Caracola grande",
  pelicano: "Pelícano vigía",
  ola: "Ola viajera",
  ballena: "Ballena azul",
  "estrella-mar": "Estrella de mar",
  hoja: "Hoja de viento",
  tambor: "Tambor del tronco",
  quena: "Quena de caña",
};

export const TOTAL_STARS = BOOKS.reduce((sum, book) => sum + book.pages.length, 0);
export const TOTAL_PINS = BOOKS.reduce(
  (sum, book) => sum + book.pages.filter((page) => page.pin).length,
  0,
);
export const TOTAL_QUIZ = BOOKS.reduce((sum, book) => sum + book.quiz.length, 0);

export function getBook(id) {
  return BOOKS.find((book) => book.id === id) || null;
}

export function bookPins(book) {
  return book.pages
    .map((page, index) => (page.pin ? { id: page.pin, page: index } : null))
    .filter(Boolean);
}
