// Adaptación infantil del texto de «Pulgarcito» aportado por Luis.
// Conserva la secuencia de aventuras; omite los detalles gráficos de violencia.
export const PULGARCITO = {
  id: "pulgarcito",
  title: "Pulgarcito",
  hero: "Pulgarcito",
  names: { pulgarcito: ["pulgarcito"], "papa-pulgarcito": ["padre", "campesino"], "mama-pulgarcito": ["mamá", "mujer"], caballo: ["caballo"], vaca: ["vaca"], lobo: ["lobo"] },
  tagline: "Pequeños pasos, grandes aventuras",
  set: "forest-day",
  accent: "#b8cf78",
  cameo: ["pulgarcito", "caracol", "caballo"],
  cover: { ink: "#ffe5a0", sub: "#d5c494", image: "/assets/nido/cuentos/covers/pulgarcito-v1.avif", titled: true, preserve: true },
  pages: [
    {
      t: "Un hijo como un pulgar",
      x: "Un campesino y su mujer deseaban tener un hijo. —Aunque fuera pequeño como mi pulgar, lo querríamos con toda el alma —decían. Un día nació un niño diminuto. Lo llamaron Pulgarcito. No crecía, pero era alegre, curioso y muy ingenioso.",
      light: "day", cast: ["papa-pulgarcito", "pulgarcito", "mama-pulgarcito"],
      props: ["casa", "flores", "pasto"], pin: "hojita-pulgarcito",
      cues: { alegre: { act: { pulgarcito: "cheer" } } },
    },
    {
      t: "En la oreja del caballo",
      x: "Su padre necesitaba llevar el carro al bosque. —¡Yo puedo ayudarte! —dijo Pulgarcito. Su mamá lo puso en la oreja del caballo. Desde allí, el pequeño le indicó el camino: —¡Arre! ¡Por aquí! El caballo avanzó con cuidado hasta encontrar al padre entre los árboles.",
      light: "day", cast: ["pulgarcito", "caballo"],
      props: ["arboles", "sendero", "hojas"], pin: "herradura",
      cues: { avanzó: { sfx: "pasos-bosque", act: { caballo: "run" } } },
    },
    {
      t: "Un viaje en el sombrero",
      x: "Dos viajeros se asombraron al ver al pequeño conductor. Querían llevarlo de pueblo en pueblo para mostrarlo. Su padre no quería separarse de él. —Volveré a casa —le susurró Pulgarcito. Y partió sentado en el ala de un sombrero, mirando el enorme mundo que lo rodeaba.",
      light: "day", cast: ["pulgarcito", "papa-pulgarcito"],
      props: ["sendero", "arboles", "nubes"], pin: "sombrero-pulgarcito",
      sfx: ["pajaros"],
    },
    {
      t: "Una casita de caracol",
      x: "Al anochecer pidió bajar y se escondió en una madriguera. Los viajeros lo buscaron, pero no lo encontraron. Cuando se alejaron, Pulgarcito salió. Entre la hierba descubrió una concha de caracol vacía. —¡Qué buena casita para pasar la noche! —dijo, y se acurrucó dentro.",
      light: "night", cast: ["pulgarcito", "concha-caracol"],
      props: ["arboles", "luna", "estrellas", "pasto"], pin: "caracol",
      acts: { pulgarcito: "sleep" },
    },
    {
      t: "Una voz muy valiente",
      x: "Dos ladrones pasaron cerca, hablando de entrar en una casa. Pulgarcito tuvo una idea para detenerlos. Se deslizó entre los barrotes y gritó muy fuerte: —¿Quieren llevarse todo lo que hay aquí? La cocinera se despertó. Encendió una vela y los ladrones huyeron sin llevarse nada.",
      light: "night", cast: ["pulgarcito"],
      props: ["casa", "arboles", "luna", "cuarto"],
      cues: { gritó: { act: { pulgarcito: "cheer" } } },
    },
    {
      t: "Entre el heno",
      x: "Cansado, Pulgarcito encontró una cama blandita en el heno del establo. Se quedó dormido pensando en volver a casa. Por la mañana, la cocinera recogió aquel heno para alimentar a la vaca. No vio al pequeño, que seguía durmiendo entre los tallitos.",
      light: "day", cast: ["pulgarcito", "vaca"],
      props: ["casa", "pasto", "sol"],
      acts: { pulgarcito: "sleep" },
    },
    {
      t: "¡La vaca habla!",
      x: "La vaca tragó el heno y Pulgarcito acabó en su barriga. —¡Basta de comida! ¡Aquí ya no cabe más! —gritó. La cocinera se llevó un susto: parecía que la vaca hablaba. Hubo un gran alboroto en el establo. Después de aquella aventura, el pequeño logró salir de allí.",
      light: "day", cast: ["vaca"],
      props: ["casa", "pasto", "flores"],
      cues: { alboroto: { act: { vaca: "shiver" } } },
    },
    {
      t: "El lobo hambriento",
      x: "Pero un lobo hambriento se lo tragó sin darse cuenta. Pulgarcito no perdió el ánimo. —Amigo lobo, conozco una casa con pan y comida deliciosa —dijo desde su barriga. Le explicó el camino hasta la casa de sus padres. El lobo corrió hacia allí, siguiendo sus indicaciones.",
      light: "dusk", cast: ["lobo"],
      props: ["arboles", "sendero", "casa"], pin: "pan-pulgarcito",
      cues: { corrió: { sfx: "pasos-bosque", act: { lobo: "run" } } },
    },
    {
      t: "¡Padre, estoy aquí!",
      x: "El lobo entró en la despensa y comió tanto que ya no cabía por la salida. Pulgarcito gritó hasta despertar a sus padres. —¡Padre, estoy aquí! ¡En la barriga del lobo! Sus padres reconocieron su voz. Con mucho cuidado lo rescataron y lo abrazaron, felices de tenerlo de vuelta.",
      light: "night", cast: ["papa-pulgarcito", "pulgarcito", "mama-pulgarcito"],
      props: ["casa", "luna", "estrellas"],
      cues: { abrazaron: { sfx: "abuelita-abrazo", act: { pulgarcito: "cheer" } } },
    },
    {
      t: "Un gran héroe pequeño",
      x: "Pulgarcito contó todas sus aventuras: la oreja del caballo, la concha del caracol, la vaca y el lobo. Sus padres le dieron comida y ropa nueva. —No volveremos a separarnos de ti por ningún tesoro —le dijeron. Pulgarcito sonrió. Era muy pequeño, pero su valor y su ingenio eran enormes.",
      light: "day", cast: ["pulgarcito", "papa-pulgarcito", "mama-pulgarcito"],
      props: ["casa", "flores", "sol", "pasto"],
      cues: { sonrió: { act: { pulgarcito: "cheer" } } },
    },
  ],
  quiz: [
    { q: "¿Por qué le pusieron Pulgarcito?", a: ["Porque era pequeño como un pulgar", "Porque era un gigante", "Porque vivía en el mar"] },
    { q: "¿Dónde se sentó para guiar al caballo?", a: ["En su oreja", "En una nube", "En un árbol"] },
    { q: "¿Dónde encontró refugio para dormir?", a: ["En una concha de caracol vacía", "En un barco", "En una torre"] },
    { q: "¿Cómo evitó que los ladrones robaran?", a: ["Gritó para despertar a la cocinera", "Les dio una llave", "Apagó todas las luces"] },
    { q: "¿Adónde guio Pulgarcito al lobo?", a: ["A la casa de sus padres", "A la luna", "Al fondo del mar"] },
  ],
};
