export const NIDO_ROLES = [
  {
    id: "administrador",
    name: "Administrador",
    description: "Gestiona clases, docentes y matrículas.",
    workspaceTitle: "Resumen de gestión",
    workspaceDescription:
      "Una vista general para organizar la operación académica de Nido.",
    metrics: [
      { value: "6", label: "clases publicadas" },
      { value: "3", label: "docentes activos" },
      { value: "47", label: "matrículas demo" },
    ],
  },
  {
    id: "docente",
    name: "Docente",
    description: "Organiza sesiones y acompaña a sus alumnos.",
    workspaceTitle: "Mi agenda docente",
    workspaceDescription:
      "Clases, materiales y acompañamiento reunidos en un solo lugar.",
    metrics: [
      { value: "2", label: "sesiones próximas" },
      { value: "18", label: "alumnos demo" },
      { value: "3", label: "materiales listos" },
    ],
  },
  {
    id: "alumno",
    name: "Alumno",
    description: "Accede a sus clases y materiales de aprendizaje.",
    workspaceTitle: "Mi aprendizaje",
    workspaceDescription:
      "Un espacio simple para encontrar próximas clases y recursos.",
    metrics: [
      { value: "2", label: "clases próximas" },
      { value: "4", label: "materiales disponibles" },
      { value: "1", label: "ruta en progreso" },
    ],
  },
];

export const NIDO_CLASSES = [
  {
    id: "vocales-aventura",
    title: "Las vocales en aventura",
    summary: "Reconocemos sonidos y letras mediante historias, ritmo y juego.",
    age: "3 a 4 años",
    course: "Comunicación",
    teacher: "Miss Valeria",
    schedule: "Mañana",
    scheduleLabel: "Sábados · 10:00 a. m.",
    duration: "45 min",
    seats: 8,
    price: 39,
    icon: "book",
    theme: "coral",
  },
  {
    id: "arte-colores",
    title: "Arte y colores",
    summary: "Exploramos formas, texturas y creatividad con proyectos guiados.",
    age: "5 a 6 años",
    course: "Arte",
    teacher: "Miss Camila",
    schedule: "Tarde",
    scheduleLabel: "Martes · 4:00 p. m.",
    duration: "50 min",
    seats: 10,
    price: 45,
    icon: "paint",
    theme: "aqua",
  },
  {
    id: "cuentos-movimiento",
    title: "Cuentos en movimiento",
    summary: "Leemos, imaginamos y expresamos cada historia con todo el cuerpo.",
    age: "5 a 6 años",
    course: "Movimiento",
    teacher: "Miss Andrea",
    schedule: "Mañana",
    scheduleLabel: "Jueves · 11:00 a. m.",
    duration: "45 min",
    seats: 7,
    price: 42,
    icon: "movement",
    theme: "yellow",
  },
  {
    id: "pequenos-cientificos",
    title: "Pequeños científicos",
    summary: "Descubrimos el mundo con preguntas y experimentos seguros en casa.",
    age: "6 años",
    course: "Ciencia",
    teacher: "Profe Diego",
    schedule: "Tarde",
    scheduleLabel: "Miércoles · 5:00 p. m.",
    duration: "55 min",
    seats: 9,
    price: 49,
    icon: "science",
    theme: "green",
  },
  {
    id: "musica-ritmo",
    title: "Música y ritmo",
    summary: "Creamos secuencias de sonido para fortalecer atención y coordinación.",
    age: "3 a 4 años",
    course: "Música",
    teacher: "Miss Andrea",
    schedule: "Tarde",
    scheduleLabel: "Viernes · 4:30 p. m.",
    duration: "40 min",
    seats: 6,
    price: 39,
    icon: "music",
    theme: "violet",
  },
  {
    id: "emociones-amistad",
    title: "Emociones y amistad",
    summary: "Aprendemos a reconocer lo que sentimos y a convivir con empatía.",
    age: "6 años",
    course: "Socioemocional",
    teacher: "Miss Camila",
    schedule: "Mañana",
    scheduleLabel: "Sábados · 11:30 a. m.",
    duration: "50 min",
    seats: 8,
    price: 45,
    icon: "heart",
    theme: "blue",
  },
];

export const NIDO_FILTERS = {
  age: ["3 a 4 años", "5 a 6 años", "6 años"],
  course: [...new Set(NIDO_CLASSES.map((classItem) => classItem.course))],
  teacher: [...new Set(NIDO_CLASSES.map((classItem) => classItem.teacher))],
  schedule: ["Mañana", "Tarde"],
};
